version: '3'
services:
  mysql:
    container_name: impdb
    restart: unless-stopped
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Imp21154
      MYSQL_USER: root2
      MYSQL_PASSWORD: Imp21154
      MYSQL_DATABASE: impardonne
    volumes:
      - ./data:/var/lib/mysql
      - ./backups:/backup # Itt tároljuk a dump fájlokat
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    restart: unless-stopped
    links:
      - mysql
    environment:
        PMA_HOST: impardonne
        PMA_PORT: 3306
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./reactlaravel/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  web-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: app-prx
    ports:
      - "80:80"
